### ISSUE TITLE
Workaround for failed installation on Arch (python 3.11 ??)

### ISSUE THREAD

**Issue by antis81** [Salamek/chromium-kiosk#77]
During installation a python exception is thrown complaining on user creation.

Running `sudo chromium-kiosk post_install` manually fixes this situation and creates/populates the `chromium-kiosk` user.

**Comment by Salamek** [comment]
Do you have copy/screenshot of that exception thrown?

**Comment by antis81** [comment]
Here is the relevant snippet from `pamac install chromium-kiosk` (up-to-date Manjaro - hence the python package versions):
 
```
…
…
Installing python-typing_extensions (4.7.1-1)...                                              [1/32]
Installing python-platformdirs (3.10.0-1)...                                                  [2/32]
Installing python-fastjsonschema (2.18.0-1)...                                                [3/32]
Installing qt6-webchannel (6.5.2-1)...                                                        [4/32]
Installing qt6-positioning (6.5.2-1)...                                                       [5/32]
Installing qt6-webengine (6.5.2-2)...                                                         [6/32]
Installing hunspell (1.7.2-1)...                                                              [7/32]
Installing qt6-virtualkeyboard (6.5.2-1)...                                                   [8/32]
Installing qiosk (1.2.2-1)...                                                                 [9/32]
Installing libxfce4util (4.18.1-1)...                                                        [10/32]
Installing python-ordered-set (4.1.0-4)...                                                   [11/32]
Installing libwnck3 (43.0-3)...                                                              [12/32]
Installing python-more-itertools (10.1.0-1)...                                               [13/32]
Installing python-jaraco.functools (3.8.1-1)...                                              [14/32]
Installing python-jaraco.context (4.3.0-3)...                                                [15/32]
Installing python-autocommand (2.2.2-4)...                                                   [16/32]
Installing python-pydantic (1.10.9-1)...                                                     [17/32]
Installing python-inflect (7.0.0-1)...                                                       [18/32]
Installing python-jaraco.text (3.11.1-3)...                                                  [19/32]
Installing python-tomli (2.0.1-3)...                                                         [20/32]
Installing python-trove-classifiers (2023.8.7-1)...                                          [21/32]
Installing python-validate-pyproject (0.13-1)...                                             [22/32]
Installing python-setuptools (1:68.0.0-1)...                                                 [23/32]
Installing xfconf (4.18.1-2)...                                                              [24/32]
Installing libxfce4ui (4.18.4-1)...                                                          [25/32]
Installing libxpresent (1.0.1-1)...                                                          [26/32]
Installing xfwm4 (4.18.0-1)...                                                               [27/32]
Installing xf86-video-fbdev (0.5.0-3)...                                                     [28/32]
Installing libev (4.33-2)...                                                                 [29/32]
Installing unclutter (1:1.6-3)...                                                            [30/32]
Installing python-websockets (10.4-3)...                                                     [31/32]
Installing chromium-kiosk (2.1.4-1)...                                                       [32/32]
Traceback (most recent call last):
  File "/usr/bin/chromium-kiosk", line 33, in <module>
    sys.exit(load_entry_point('chromium-kiosk==2.1.4', 'console_scripts', 'chromium-kiosk')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/chromium_kiosk/__main__.py", line 5, in main
    _main()
  File "/usr/lib/python3.11/site-packages/chromium_kiosk/bin/chromium_kiosk.py", line 390, in main
    getattr(command, 'chosen')()  # Execute the function specified by the user.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/chromium_kiosk/bin/chromium_kiosk.py", line 297, in post_install
    uid = pwd.getpwnam(config.USER).pw_uid
          ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: "getpwnam(): name not found: 'chromium-kiosk'"
Error while configuring chromium-kiosk
Created symlink /etc/systemd/system/multi-user.target.wants/chromium-kiosk_configwatcher.service → /usr/lib/systemd/system/chromium-kiosk_configwatcher.service.
Running post-transaction hooks...
Creating system user accounts...                                                               [1/6]
Creating group 'chromium-kiosk' with GID 963.
Creating user 'chromium-kiosk' (Chromium based web kiosk) with UID 963 and GID 963.
Reloading system manager configuration...                                                      [2/6]
Arming ConditionNeedsUpdate...                                                                 [3/6]
Updating GIO module cache...                                                                   [4/6]
Updating icon theme caches...                                                                  [5/6]
Updating the desktop file MIME type cache...                                                   [6/6]
A restart is required for the changes to take effect.
Transaction successfully finished.
```

**Comment by Salamek** [comment]
This should be fixed now since we are using sysusers.d and tmpfiles.d to manage chromium-kiosk user and home dir, post_install is not called during installation anymore but i did not test it...

**Comment by Salamek** [comment]
Ok i suppose this is fixed now, closing...

**Comment by antis81** [comment]
Sorry I cannot verify it, because the environment has changed completely…

**Comment by Salamek** [comment]
@antis81 its fine, i just tested it on fresh install of Archlinux :-)
