### ISSUE TITLE
Remote debugging - exception

### ISSUE THREAD

**Issue by kalwinskidawid** [Salamek/chromium-kiosk#95]
Hey, I have a problem with **remote debug**, if I uncomment it then I cannot run `chromium-kiosk run`, exception below. 
If I comment remote debug, chromium launches normally. 

In general, I'm trying to put up some lightweight Linux that will only display the browser and I chose [miniOS](https://minios.dev/en/#downloads). 

Linux version: 
```
Linux minios 6.1.90-mos-amd64 #1 SMP PREEMPT_DYNAMIC Wed Jun  5 18:31:22 UTC 2024 x86_64 GNU/Linux
```
Exception:
```
chromium-kiosk@minios:~$ chromium-kiosk run
xrandr: Failed to get size of gamma for output default
xrandr: Failed to get size of gamma for output default
Traceback (most recent call last):
  File "/usr/bin/chromium-kiosk", line 33, in <module>
    sys.exit(load_entry_point('chromium-kiosk==2.6.0', 'console_scripts', 'chromium-kiosk')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/chromium_kiosk/__main__.py", line 5, in main
    _main()
  File "/usr/lib/python3/dist-packages/chromium_kiosk/bin/chromium_kiosk.py", line 308, in main
    getattr(command, 'chosen')()  # Execute the function specified by the user.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/chromium_kiosk/bin/chromium_kiosk.py", line 236, in run
    selected_browser.run()
  File "/usr/lib/python3/dist-packages/chromium_kiosk/Qiosk.py", line 206, in run
    subprocess.call(self._build_command(), env=self._build_env())
  File "/usr/lib/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1821, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
                               ^^^^^^^^^^^^^^
  File "<frozen os>", line 812, in fsencode
TypeError: expected str, bytes or os.PathLike object, not int
```

Config:
```
FULL_SCREEN: true # Run in full screen mode, browser will use whole screen without any way for user to close it
TOUCHSCREEN: true # Enables support for touchscreen
HOME_PAGE: 'http://10.35.20.20:85'  # Url to load as homepage
 
IDLE_TIME: 0 # Seconds, How log must be kiosk idle to redirect to HOME_PAGE, 0=disabled
WHITE_LIST:
  ENABLED: true  # is white list enabled
  URLS: ['http://10.35.20.20:85/**']   # List of whitelisted urls, glob format is supported (eg,: *,google.*/news)
  IFRAME_ENABLED: true  # True to enable all iframes, list of urls to specify enabled iframes
 
NAV_BAR:
  ENABLED: false # is nav bar enabled
  ENABLED_BUTTONS: ['home', 'reload', 'back', 'forward'] # Enabled buttons on navbar, order matters
  HORIZONTAL_POSITION: 'center' # horizontal position on the screen
  VERTICAL_POSITION: 'bottom' # Vertical position on the screen
  WIDTH: 100 # Width of a bar in %
  HEIGHT: 5 # Height of a bar in %
  UNDERLAY: false  # true to display navbar under the web view
 
VIRTUAL_KEYBOARD:
  ENABLED: true
 
DISPLAY_ROTATION: 'normal' # normal|left|right|inverted
#SCREEN_ROTATION: 'normal'  #Rotates screen individually (do not rotate touchscreen) when X server starts options are (normal|left|right|inverted), remove DISPLAY_ROTATION for this to work
#TOUCHSCREEN_ROTATION: 'normal'  #Rotates touchscreen individually (do not rotate screen) when X server starts options are (normal|left|right|inverted), remove DISPLAY_ROTATION for this to work
#EXTRA_ARGUMENTS: # Pass extra arguments to used browser, in case of qiosk thse arguments are passed to chromium using QTWEBENGINE_CHROMIUM_FLAGS
 
 
#ADDRESS_BAR:
#  ENABLED: false  # Show/hide address bar
 
#SCROLL_BARS:
#  ENABLED: false  # Show hide scroll bars
 
# Allowed features in browser
# Uncomment feature you want to enable
#ALLOWED_FEATURES:
#  - desktop-audio-video-capture  # Allows recording desktop audio and video
#  - desktop-video-capture  # Allows recording desktop video
#  - geolocation  # Allows geolocation
#  - invalid-certificate  # Ignores invalid certificate
#  - media-audio-capture  # Allows recording audio from capture device (MIC)
#  - media-audio-video-capture  # Allows recording audio and video from capture device (Camera w/ MIC)
#  - media-video-capture  # Allows recording vide from capture device (Camera)
#  - mouse-lock  # Allows locking mouse inside browser full screen window
#  - notifications  # Allows notifications to be accepted from website
 
REMOTE_DEBUGGING:  9988 # Set to port number to enable available only when using qiosk browser
 
# EXTRA_ENV_VARS:  # Extra env vars set to the kiosk session
#    VAR_NAME: VAR_VALUE
 
# PROFILE_NAME: 'default' # Name of profile to use, default for default off-the-record profile
 
#CURSOR:
#    ENABLED: true  # Cursor enabled by default
```

**Comment by Salamek** [comment]
@kalwinskidawid should be fixed in latest release
